-- GROUP BY / HAVING
SELECT P.NOME, MAX(M.VALOR)
FROM PESSOA P INNER JOIN MISSAO M
            ON P.CADASTRO = M.CADASTRO
GROUP BY(P.NOME)
HAVING MAX(M.VALOR) > 5000

-- 
v


-- SEMELHANTE AO EXEMPLO
CREATE OR REPLACE PROCEDURE EXIBE_QT_MISSOES_TIME IS QT NUMBER;
BEGIN
    SELECT COUNT(*) INTO QT FROM TIME_FAZ_MISSAO WHERE NUMERO_DO_TIME = 3;
    DBMS_OUTPUT.PUT_LINE('QUANTIDADE DE ARTIGOS: '||QT);
END;
--OU
CREATE OR REPLACE FUNCTION GET_QT_MISSOES_TIME RETURN NUMBER IS QT NUMBER;
BEGIN
    SELECT COUNT(*) INTO QT FROM TIME_FAZ_MISSAO WHERE NUMERO_DO_TIME = 3;
    RETURN QT;
END;
--OU 
CREATE OR REPLACE PROCEDURE EXIBE_QT_MISSOES_TIME(NUM IN NUMBER) IS QT NUMBER;
BEGIN
    SELECT COUNT(*) INTO QT FROM TIME_FAZ_MISSAO WHERE NUMERO_DO_TIME = NUM;
    DBMS_OUTPUT.PUT_LINE('QUANTIDADE DE ARTIGOS: '||QT);
END;
--OU
CREATE OR REPLACE FUNCTION GET_QT_MISSOES_TIME(NUM IN NUMBER) RETURN NUMBER IS QT NUMBER;
BEGIN
    SELECT COUNT(*) INTO QT FROM TIME_FAZ_MISSAO WHERE NUMERO_DO_TIME = NUM;
    RETURN QT;
END;